"""file processing, thumbnails

Revision ID: 382a8e305932
Revises: f16d8a836227
Create Date: 2026-03-12 20:31:25.660055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = '382a8e305932'
down_revision: Union[str, Sequence[str], None] = 'f16d8a836227'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('thumbnails',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('track_id', sa.UUID(), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index(op.f('ix_thumbnails_track_id'), 'thumbnails', ['track_id'], unique=False)
    op.sync_enum_values(
        enum_schema='public',
        enum_name='track_file_status',
        new_values=['PENDING', 'PROCESSING', 'READY', 'FAILED'],
        affected_columns=[TableReference(table_schema='public', table_name='track_files', column_name='status', existing_server_default="'PENDING'::track_file_status")],
        enum_values_to_rename=[],
    )
    op.sync_enum_values(
        enum_schema='public',
        enum_name='track_status',
        new_values=['DRAFT', 'PROCESSING', 'READY', 'FAILED'],
        affected_columns=[TableReference(table_schema='public', table_name='tracks', column_name='status')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='track_status',
        new_values=['DRAFT', 'PROCESSING', 'READY', 'PUBLISHED', 'FAILED'],
        affected_columns=[TableReference(table_schema='public', table_name='tracks', column_name='status')],
        enum_values_to_rename=[],
    )
    op.sync_enum_values(
        enum_schema='public',
        enum_name='track_file_status',
        new_values=['PENDING', 'UPLOADED', 'PROCESSING', 'READY'],
        affected_columns=[TableReference(table_schema='public', table_name='track_files', column_name='status', existing_server_default="'PENDING'::track_file_status")],
        enum_values_to_rename=[],
    )
    op.drop_index(op.f('ix_thumbnails_track_id'), table_name='thumbnails')
    op.drop_table('thumbnails')
    # ### end Alembic commands ###
