"""track_visibility, trackfile

Revision ID: 44474bf7b5c0
Revises: f7b3a4c9d8e1
Create Date: 2026-03-08 16:43:41.787629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '44474bf7b5c0'
down_revision: Union[str, Sequence[str], None] = 'f7b3a4c9d8e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('PRIVATE', 'UNLISTED', 'PUBLIC', name='track_visibility').create(op.get_bind())
    op.create_table('track_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('track_id', sa.UUID(), nullable=False),
    sa.Column('file_type', sa.String(length=20), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index(op.f('ix_track_files_file_type'), 'track_files', ['file_type'], unique=False)
    op.create_index(op.f('ix_track_files_track_id'), 'track_files', ['track_id'], unique=False)
    op.add_column('tracks', sa.Column('visibility', postgresql.ENUM('PRIVATE', 'UNLISTED', 'PUBLIC', name='track_visibility', create_type=False), server_default='PUBLIC', nullable=False))
    op.create_index(op.f('ix_tracks_visibility'), 'tracks', ['visibility'], unique=False)
    op.sync_enum_values(
        enum_schema='public',
        enum_name='track_status',
        new_values=['DRAFT', 'PROCESSING', 'READY', 'PUBLISHED', 'FAILED'],
        affected_columns=[TableReference(table_schema='public', table_name='tracks', column_name='status')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='track_status',
        new_values=['DRAFT', 'PROCESSING', 'PUBLISHED'],
        affected_columns=[TableReference(table_schema='public', table_name='tracks', column_name='status')],
        enum_values_to_rename=[],
    )
    op.drop_index(op.f('ix_tracks_visibility'), table_name='tracks')
    op.drop_column('tracks', 'visibility')
    op.drop_index(op.f('ix_track_files_track_id'), table_name='track_files')
    op.drop_index(op.f('ix_track_files_file_type'), table_name='track_files')
    op.drop_table('track_files')
    sa.Enum('PRIVATE', 'UNLISTED', 'PUBLIC', name='track_visibility').drop(op.get_bind())
    # ### end Alembic commands ###
