"""track,genre,instrument,mood,tag

Revision ID: a09c1af79be8
Revises: d2f180baefc1
Create Date: 2026-03-05 10:08:13.394669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a09c1af79be8'
down_revision: Union[str, Sequence[str], None] = 'd2f180baefc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('DRAFT', 'PROCESSING', 'PUBLISHED', name='track_status').create(op.get_bind())
    op.create_table('genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_genres_name'), 'genres', ['name'], unique=True)
    op.create_table('instruments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instruments_name'), 'instruments', ['name'], unique=True)
    op.create_table('moods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_moods_name'), 'moods', ['name'], unique=True)
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    op.create_table('tracks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('bpm', sa.Integer(), nullable=True),
    sa.Column('root_note', sa.String(length=2), nullable=True),
    sa.Column('scale_type', sa.String(length=10), nullable=True),
    sa.Column('status', postgresql.ENUM('DRAFT', 'PROCESSING', 'PUBLISHED', name='track_status', create_type=False), nullable=False),
    sa.Column('waveform_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(root_note IS NULL) OR root_note IN ('C','C#','D','D#','E','F','F#','G','G#','A','A#','B')", name='check_root_note'),
    sa.CheckConstraint("(scale_type IS NULL) OR scale_type IN ('major','minor')", name='check_scale_type'),
    sa.CheckConstraint('(bpm IS NULL) OR (bpm > 0 AND bpm <= 300)', name='check_bpm_range'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tracks_status'), 'tracks', ['status'], unique=False)
    op.create_index(op.f('ix_tracks_user_id'), 'tracks', ['user_id'], unique=False)
    op.create_table('track_genres',
    sa.Column('track_id', sa.UUID(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('track_id', 'genre_id')
    )
    op.create_table('track_instruments',
    sa.Column('track_id', sa.UUID(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('track_id', 'instrument_id')
    )
    op.create_table('track_moods',
    sa.Column('track_id', sa.UUID(), nullable=False),
    sa.Column('mood_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mood_id'], ['moods.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('track_id', 'mood_id')
    )
    op.create_table('track_tags',
    sa.Column('track_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('track_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('track_tags')
    op.drop_table('track_moods')
    op.drop_table('track_instruments')
    op.drop_table('track_genres')
    op.drop_index(op.f('ix_tracks_user_id'), table_name='tracks')
    op.drop_index(op.f('ix_tracks_status'), table_name='tracks')
    op.drop_table('tracks')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_moods_name'), table_name='moods')
    op.drop_table('moods')
    op.drop_index(op.f('ix_instruments_name'), table_name='instruments')
    op.drop_table('instruments')
    op.drop_index(op.f('ix_genres_name'), table_name='genres')
    op.drop_table('genres')
    sa.Enum('DRAFT', 'PROCESSING', 'PUBLISHED', name='track_status').drop(op.get_bind())
    # ### end Alembic commands ###
