"""slugs for mood,genre,instruments

Revision ID: e1052da65a67
Revises: a09c1af79be8
Create Date: 2026-03-05 12:14:45.443144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1052da65a67'
down_revision: Union[str, Sequence[str], None] = 'a09c1af79be8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('genres', sa.Column('slug', sa.String(length=50), nullable=False))
    op.drop_index(op.f('ix_genres_name'), table_name='genres')
    op.create_index(op.f('ix_genres_slug'), 'genres', ['slug'], unique=True)
    op.create_unique_constraint(None, 'genres', ['name'])
    op.add_column('instruments', sa.Column('slug', sa.String(length=50), nullable=False))
    op.drop_index(op.f('ix_instruments_name'), table_name='instruments')
    op.create_index(op.f('ix_instruments_slug'), 'instruments', ['slug'], unique=True)
    op.create_unique_constraint(None, 'instruments', ['name'])
    op.add_column('moods', sa.Column('slug', sa.String(length=50), nullable=False))
    op.drop_index(op.f('ix_moods_name'), table_name='moods')
    op.create_index(op.f('ix_moods_slug'), 'moods', ['slug'], unique=True)
    op.create_unique_constraint(None, 'moods', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'moods', type_='unique')
    op.drop_index(op.f('ix_moods_slug'), table_name='moods')
    op.create_index(op.f('ix_moods_name'), 'moods', ['name'], unique=True)
    op.drop_column('moods', 'slug')
    op.drop_constraint(None, 'instruments', type_='unique')
    op.drop_index(op.f('ix_instruments_slug'), table_name='instruments')
    op.create_index(op.f('ix_instruments_name'), 'instruments', ['name'], unique=True)
    op.drop_column('instruments', 'slug')
    op.drop_constraint(None, 'genres', type_='unique')
    op.drop_index(op.f('ix_genres_slug'), table_name='genres')
    op.create_index(op.f('ix_genres_name'), 'genres', ['name'], unique=True)
    op.drop_column('genres', 'slug')
    # ### end Alembic commands ###
