"""trackfile status

Revision ID: f16d8a836227
Revises: 44474bf7b5c0
Create Date: 2026-03-09 11:11:26.777375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f16d8a836227'
down_revision: Union[str, Sequence[str], None] = '44474bf7b5c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('PENDING', 'UPLOADED', 'PROCESSING', 'READY', name='track_file_status').create(op.get_bind())
    op.add_column('track_files', sa.Column('status', postgresql.ENUM('PENDING', 'UPLOADED', 'PROCESSING', 'READY', name='track_file_status', create_type=False), server_default='PENDING', nullable=False))
    op.create_index(op.f('ix_track_files_status'), 'track_files', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_track_files_status'), table_name='track_files')
    op.drop_column('track_files', 'status')
    sa.Enum('PENDING', 'UPLOADED', 'PROCESSING', 'READY', name='track_file_status').drop(op.get_bind())
    # ### end Alembic commands ###
